version: '3.7'

services:
  worker:
    build: .
    environment:
      AMQP_URI: ${AMQP_URI}
      PROCESSOR_EVENT_FILE: "/stream-processor/sampled_rc.json"
      PROCESSOR_RESULTS_OUTFILE: "/stream-processor/results.json"
    volumes:
      - .:/stream-processor
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}

  flower:  
    image: mher/flower
    environment:
      CELERY_BROKER_URL: ${AMQP_URI}
      FLOWER_PORT: 8888
    ports:  
      - 8888:8888
